import type { NextPageWithLayout } from './_app';
import SearchLayout from '@layouts/SearchLayout';
import Head from 'next/head';
import { ReactElement } from 'react';

const SearchPage: NextPageWithLayout = () => {
    return (<>
        <Head>
            <title>Search</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div>
            
        </div>
    
    </>);
}

SearchPage.getLayout = (page: ReactElement) => (<SearchLayout>{page}</SearchLayout>)

export default SearchPage;